on:
  pull_request:
    types: [opened, synchronize]

jobs:

  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo
        ports:
          - "27017:27017"
        options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
      - name: MongoDB Query Evaluator Step
        uses: betrybe/mongodb-query-evaluator-action@prepara-avaliador-para-v3
        id: evaluator
        env:
          DBNAME: 'dataFlights'
        with:
          repository-import-folder: 'assets'
          repository-challenges-folder: 'challenges'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}
